### ISSUE TITLE
V6_Plenum[2020_extrusion].stl print issue

### ISSUE THREAD

**Issue by Marshalldog** [nevermore3d/Nevermore_Micro#46]
I love the v6 but the current print orientation for the "V6_Plenum[2020_extrusion].stl" is problematic. the print orientation of the stl positions a long, thin, edge, which makes the design highly susceptible to warping (especially considering the recommended material being abs). I tried multiple times to print it with an enclosed voron 2.4 with a chamber temp above 40 but the print consistently warped to the point of being unusable (because the magnetic warped too far away from the correct position. I'd recommend a version of the design with a print orientation like the v5 "V2_Duo_Plenum.stl" to reduce warping.

**Comment by 0ndsk4** [comment]
thanks for the suggestion - unfortunately, the printing direction is one of the pros of the upgrade, allowing the built in seals that prevent air leaks. it has been printed by plenty of people in regular abs, so your issue is most likely a settings/surface issue. If you want something micro sized and dont overcome these difficulties, the v5 has a different printing direction. thanks.
