### ISSUE TITLE
V6 Plenum wall too thin.

### ISSUE THREAD

**Issue by Matt2916** [nevermore3d/Nevermore_Micro#47]
The wall on the upper right hand of the V6_Plenum is too thin and slices with a tiny hole.
![nevermore_v6](https://github.com/nevermore3d/Nevermore_Micro/assets/139070636/1340659a-3344-4f17-8aff-be41b0133275)

**Comment by 0ndsk4** [comment]
Thx. This was noted on discord too. Expect a fix when back from vacationing. It’s possible to slice the wall continuously tweaking the slicer settings, which is why this wasn’t noticed earlier - however, there will always be a surface imperfection from being just a single wall. This will be updated.

**Comment by Matt2916** [comment]
My v5 works still fine, so I'll wait for the update - have a great vacation!

**Comment by 0ndsk4** [comment]
issue has now been fixed in alla files, thanks!
