### ISSUE TITLE
Why push air thrue filter?

### ISSUE THREAD

**Issue by Shedatheds** [nevermore3d/Nevermore_Micro#72]
Why is the filter not on intake side of the fan at V6? It would be more efficient to have the filter on intake side!

**Comment by 0ndsk4** [comment]
Originally due to the space constraints under the bed of the voron v2.4. And while a push configuration can be more efficient, it’s also true that’s not the case with a highly restrictive filter in front of fast airflow. 

It would likely take a thicker version to achieve the intake space needed for rotated fans. Then again, it wouldn’t come near a nevermore mini in airflow, and a mini is not that much thicker… feel free to mod the micro tho :)
